### ISSUE TITLE
Simple example panics

### ISSUE THREAD

**Issue by AdamNiederer** [chrisduerr/leechbar#29]
Hey, thanks for making this library! I'm encountering a panic when I try to run any examples.

```
thread 'main' panicked at 'Unable to get primary output crtc information: Error { ptr: 0x7f977da454b0 }', libcore/result.rs:945:5
stack backtrace:
   0:     0x564aff54689b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h085b5cb2919943dc
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x564aff54d280 - std::sys_common::backtrace::print::he25c82f98f7aac81
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x564aff53d500 - std::panicking::default_hook::{{closure}}::hc30a4462d8c591a0
                               at libstd/panicking.rs:380
   3:     0x564aff53d257 - std::panicking::default_hook::hcb9c5feec9166013
                               at libstd/panicking.rs:396
   4:     0x564aff53d94b - std::panicking::rust_panic_with_hook::h9f5570af4bf0234b
                               at libstd/panicking.rs:576
   5:     0x564aff53d80e - std::panicking::begin_panic::hc973540f5677dae3
                               at libstd/panicking.rs:537
   6:     0x564aff53d70a - std::panicking::begin_panic_fmt::habd3beed8a63031a
                               at libstd/panicking.rs:521
   7:     0x564aff53d6a2 - rust_begin_unwind
                               at libstd/panicking.rs:497
   8:     0x564aff58ffb0 - core::panicking::panic_fmt::hc0bf389917b16633
                               at libcore/panicking.rs:71
   9:     0x564aff429c38 - core::result::unwrap_failed::h393f698bfb8cccb1
                               at /checkout/src/libcore/macros.rs:23
  10:     0x564aff428d3d - <core::result::Result<T, E>>::expect::hedaa7ff381d77d38
                               at /checkout/src/libcore/result.rs:809
  11:     0x564aff418120 - leechbar::bar::primary_screen_info::hc0b8df8c6c679a04
                               at src/bar.rs:408
  12:     0x564aff417449 - leechbar::bar::screen_info::hf2927b171988f0cb
                               at src/bar.rs:340
  13:     0x564aff414892 - leechbar::bar::Bar::new::h8015909145a37f91
                               at src/bar.rs:54
  14:     0x564aff413ff9 - leechbar::builder::BarBuilder::spawn::h2fef54c5fb31fda4
                               at src/builder.rs:223
  15:     0x564aff401b88 - simple::main::hf3b013c8a12622df
                               at examples/simple.rs:26
  16:     0x564aff401788 - std::rt::lang_start::{{closure}}::haa29a9e489c2bc6c
                               at /checkout/src/libstd/rt.rs:74
  17:     0x564aff53d607 - std::panicking::try::do_call::hb11c25abdfc27ad2
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:479
  18:     0x564aff55520e - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  19:     0x564aff541c83 - std::rt::lang_start_internal::ha082c8a960712b5c
                               at libstd/panicking.rs:458
                               at libstd/panic.rs:358
                               at libstd/rt.rs:58
  20:     0x564aff401774 - std::rt::lang_start::hd8ed062ce71df610
                               at /checkout/src/libstd/rt.rs:74
  21:     0x7f9780ec9f49 - __libc_start_main
  22:     0x564aff3f8e89 - _start
  23:                0x0 - <unknown>

```

xrandr output:
```
HDMI-A-3 connected 1920x1080+0+0 (0xa8) normal (normal left inverted right x axis y axis) 509mm x 286mm
	Subpixel:   horizontal rgb
	Gamma:      1.0:1.0:1.0
	Brightness: 1.0
	Clones:    
	CRTC:       0
	CRTCs:      0 1 2 3 4 5
```
library versions:
```
libxcb 1.12-1
libxrandr 1.5.1-2
xorg-server 1.19.6+13+gd0d1a694f-1
```
Let me know if I can provide any other info that might assist in debugging.

**Comment by chrisduerr** [comment]
This happens when you have only a single monitor but it is not set to be your primary output.

It should be fixed by running `xrandr --output <OUTPUT> --primary`.
